### PR TITLE
MakieExt

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
@daanhb I think this is a reasonable first pass: we can do some simple 2D and 3D geometries.

Since codecov isn't working I haven't added tests yet. Do you think we can get that resolved?

I had a similar issue on another repository that I haven't figured out how to fix, so this really is just a ploy to get you to figure that out 😂

**Review by daanhb — APPROVED** [review]

**Comment by daanhb** [comment]
Looks good to me, we can always expand later. I don't know what happened to codecov yet, it seems to have stopped after merging a compathelper change, but that seems totally unrelated.

**Comment by dlfivefifty** [comment]
OK we'll have to find someone else with a repository with codecov not working to trick into debugging it for us. I'll add some tests just for fun

**Comment by daanhb** [comment]
This is the problem https://docs.codecov.com/docs/adding-the-codecov-token
working on it

**Comment by daanhb** [comment]
More info about the problem here: https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

It was a breaking change in codecov action v4, for which you need to add a token (to be obtained from codecov website) to the github action settings. I just followed the steps listed there and changed ci.yml to be like what it is e.g. here: https://github.com/SciML/DifferentialEquations.jl/blob/master/.github/workflows/CI.yml

Codecov just updated.

**Pull request merged**
