### PR TITLE
fix definition of Z, R, N and Q (#94)

### PR DESCRIPTION
**Pull request by daanhb**
#94

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Why remove them when implementing is very straightforward?

**Comment by daanhb** [comment]
Did you have an implementation in mind? I was thinking we could make a strict "StrictFullSpace{T}" (or something with a better name) which contains `x` if `x` is of type `T`, or if `convert(T, x)` works. That might be useful elsewhere too.

**Comment by daanhb** [comment]
It's like a `TypeDomain`, the domain of all instances of a certain type

**Comment by dlfivefifty** [comment]
Why not:
```julia
struct Integers end
in(x, ::Integers) = isinteger(x)
```

**Comment by daanhb** [comment]
I've done both, more strict full spaces called `TypeDomain` and specific number sets like `Integers`. The `isinteger` function seems indeed most appropriate to define the set of integers. The `isreal` function allows real arrays (intentionally), so I had to exclude those for the set of real numbers. It's a pity there are no generic functions `isnumber`, `iscomplex` and `isrational`.

Anyway:
```julia
julia> π ∈ ℤ
false
```

**Pull request merged**
