### PR TITLE
rename isopen/isclosed/iscompact

### PR DESCRIPTION
**Pull request by daanhb**
Reflecting the rename in IntervalSets version 0.5, we rename isopen/isclosed to isopenset/isclosedset. It seems to make sense to rename iscompact to iscompact set as well.

### CODE REVIEW

**Comment by daanhb** [comment]
I have kept `iscompact` like it was, instead of renaming it to `compactset`. It has to stop somewhere, we also have `isempty` and that is defined in Base for collections. This pull request supersedes #59.

**Comment by dlfivefifty** [comment]
Shall we get this merged and tagged?

**Comment by daanhb** [comment]
If it no longer breaks things - then yes

**Comment by daanhb** [comment]
This pull request does not change the version number, so 0.3.0 would include both the "vector" changes and the renames, which I guess is fine

**Comment by dlfivefifty** [comment]
Yes that’s fine

**Pull request merged**
