### PR TITLE
Move show for `Point` from `ApproxFun`

### PR DESCRIPTION
**Pull request by jishnub**
On master
```julia
julia> Point(3)
Point{Int64}(3)

julia> Point(3.0)
Point{Float64}(3.0)
```
This PR
```julia
julia> Point(3)
Point(3)

julia> Point(3.0)
Point(3.0)
```

### CODE REVIEW

**Comment by jishnub** [comment]
Test failures seem unrelated

**Comment by daanhb** [comment]
Looks good, thanks

**Comment by daanhb** [comment]
@jishnub do you want this released? I think we could do that

**Comment by jishnub** [comment]
Yes. please tag this

**Pull request merged**
