### PR TITLE
Product center

### PR DESCRIPTION
**Pull request by philip-stuckey**
added center for `ProductDomain` to resolve issue #137

### CODE REVIEW

**Comment by daanhb** [comment]
Looks good, thanks. You could put a test somewhere in the `test_product_domain` function (which starts [here](https://github.com/JuliaApproximation/DomainSets.jl/blob/92f72b02df675da49482e93541fd53764cb597a2/test/test_domain_product.jl#L3)) to trigger a test of the line that was added. A test for rectangles is probably fine and would ensure that the case you initially cared about would continue to work.

**Comment by philip-stuckey** [comment]
I want to change some things (I think `hcat` was the wrong cat to use).

**Comment by daanhb** [comment]
Hmm, it might be a bit more complicated after all. While `vcat` works, it will return a Vector for rectangles, even if the `eltype` of the domain is `SVector`.

There is a generic routine to turn points of the composing domains into a point of the product domain, namely `toexternalpoint`. Could you try this definition: ```DomainSets.toexternalpoint(d, map(center, components(d)))```?

**Comment by philip-stuckey** [comment]
so I'm just spitballing here, but a function like `bar(d::Domain{T}, y::U) where {T, U} = promote_type(T, U)(y)` seems to work. `bar(d, map(center, components(d)))` gives `SVector{2, Float64}(0.5,0.5)` when `d = (0..1)×(0..1) `.

**Comment by daanhb** [comment]
I'm actually okay with the error thrown when using Integer intervals. Either the user intends to use integers, in which case the center is not defined, or the user wants to use floating point numbers, in which case the solution is not to use integer intervals in the first place and the error signals the problem. I.e., the solution here is not to fix `center` for products of integer intervals, but to prevent the latter from being constructed in the first place. (There is an ongoing discussion about changing that behaviour but there are valid arguments either way.)

**Comment by philip-stuckey** [comment]
ok, that's probably fine then. It id a bit annoying because I'll have to remember to that that specific `InexactError` is the result of a rectangle made of intervals with integer bounds. But probably that relates to the bigger issue that I don't really want to get into (probably the pedantic thing to do would be to open an issue about `tointernalpoint` or something. but I;m not feeling *that* pedantic today).

**Comment by daanhb** [comment]
I'd merge, but following my suggestion now the code has an unnecessary `DomainSets.` qualifier (right?) and used `components` again rather than `factors`. The ratio of commits is already high compared to the number of lines affected anyway, how about one more :-) :-)

**Comment by daanhb** [comment]
Perhaps make it version 0.6.7 in Project.toml while you're at it?

**Pull request merged**
